server:
  port: 5090
  servlet:
    session:
      timeout: 1m
spring:
  application:
    name: fes-web
  redis:
    # Redis数据库索引（默认为0）
    database: 8
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: redis@Miniw
    # 连接超时时间
    timeout: 60s

    jedis:
      pool:
        # 最大连接数
        max-active: 1500
        # 最大空闲线程
        max-idle: 5
        # 最小空闲线程
        min-idle: 0
        # 最大连接阻塞时间，负值表示没有限制
        max-wait: 30s
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mini-festival?useUnicode=true&characterEncoding=utf8
    password: 123@Miniw
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 初始化大小，最小，最大
      minimum-idle: 1
      maximum-pool-size: 10
      # 空闲超时时间
      idle-timeout: 600000
      # 配置获取连接等待超时的时间
      connection-timeout: 10000
      #下面这两个配置，可以在每次连接的时候判断一些连接是否有效
      connection-test-query: select 1

# 迷你玩GameApi
gameapi:
  profiles:
    active: test

# 邮件测试服URL
mini-email:
  sendurl: 120.24.64.132:8087


# slf4j
logging:
  level:
    org.springframework.web: ERROR
    com.miniw: DEBUG
